welcome = "Welcome to iris framework!"

[api]


[app]
  debug = false
  host = "0.0.0.0"
  name = "iris-app"
  port = 8080

  [app.logger]
    format = "2006/01/02 15:04:05"
    level = "debug"
    name = "application"

[auth]


[database]
  driver = "mysql"

[mysql]
  charset = "utf8"
  databaseName = "vulnerability_management"
  databasePassword = "123456"
  databaseUserName = "root"
  host = "192.168.248.109"
  port = 3306

[notice]


[systemurl]
 

[upload]

